# =========================
# Hypridle - Auto lock + screen off
# No suspend
# =========================

general {
    lock_cmd = pgrep -x hyprlock >/dev/null || hyprlock
    before_sleep_cmd = pgrep -x hyprlock >/dev/null || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = pgrep -x hyprlock >/dev/null || hyprlock
}

# Turn screen off after 7 minutes
listener {
    timeout = 420
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
