# =========================
# Basic Hyprland config
# =========================

$mod = SUPER
$terminal = kitty
$menu = fuzzel

# Monitor
monitor=,preferred,auto,1

# Startup apps
#exec-once = waybar
#exec-once = dunst
exec-once = swaync
exec-once = bash -lc 'pgrep -x nm-applet >/dev/null || nm-applet --indicator'
exec-once = bash -lc 'pgrep -x blueman-applet >/dev/null || blueman-applet'
exec-once = ~/.local/bin/start-video-wallpaper
exec-once = bash -lc 'pgrep -x swaync >/dev/null || swaync'
exec-once = bash -lc 'pgrep -x hypridle >/dev/null || hypridle'
exec-once = hyprctl setcursor Bibata-Modern-Classic 24




# Basic environment
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24

env = GTK_THEME,Adwaita:dark




# Input
input {
    kb_layout = latam
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

# General look
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 4
        passes = 2
    }
}

animations {
    enabled = true
}

dwindle {
    preserve_split = true
}

# Keybinds
bind = $mod, Q, exec, $terminal
bind = $mod, R, exec, $menu
bind = $mod, C, killactive
bind = $mod, M, exit
bind = $mod, F, fullscreen
bind = $mod, V, togglefloating
bind = $mod SHIFT, B, exec, ~/.local/bin/toggle-waybar
bind = $mod SHIFT, W, exec, ~/.local/bin/toggle-video-wallpaper
bind = SUPER, N, exec, swaync-client -t
bind = SUPER, L, exec, hyprlock

# Move focus
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Screenshots
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -
bind = SHIFT, Print, exec, grim "$HOME/Pictures/Screenshots/screenshot-$(date +%F-%H-%M-%S).png"
bind = SUPER, Print, exec, grim -g "$(slurp)" "$HOME/Pictures/Screenshots/screenshot-$(date +%F-%H-%M-%S).png"
bind = SUPER SHIFT, S, exec, grim -g "$(slurp)" "$HOME/Pictures/Screenshots/screenshot-$(date +%F-%H-%M-%S).png"

# Laptop function/media keys

# Volume
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Microphone mute
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Media playback
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioStop, exec, playerctl stop
