# =========================
# Hyprlock - Dark Red Setup
# =========================

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 8
    noise = 0.0117
    contrast = 1.1
    brightness = 0.65
    vibrancy = 0.2
    vibrancy_darkness = 0.5
}

label {
    monitor =
    text = archomen
    color = rgba(ff3333ff)
    font_size = 34
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(f8f8f2ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = Enter your password
    color = rgba(f8f8f2cc)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -45
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true

    outer_color = rgba(ff3333ff)
    inner_color = rgba(050505cc)
    font_color = rgba(f8f8f2ff)
    check_color = rgba(f1fa8cff)
    fail_color = rgba(ff3333ff)

    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    fail_text = <i>Wrong password</i>

    position = 0, -110
    halign = center
    valign = center
}
